/* ============================================================================
 * HOW TO USE THESE TESTS
 * ============================================================================
 * Open tests.html in your browser (not index.html).
 * You will see a list of tests — red means failing, green means passing.
 * At the start, almost all tests will be red. That is expected.
 * As you implement each function in game.js, re-open tests.html to see your
 * progress.
 * Your goal: all tests green.
 *
 * The tests are READ-ONLY. Do not edit this file.
 * All your work goes in game.js and ui.js.
 * ========================================================================== */

(function () {
  'use strict';

  /* --- A tiny test runner ------------------------------------------------- */
  const results = [];

  /**
   * Run one test. If `fn` throws, the test fails and we record the error.
   * Nothing the student does can crash the whole page — every test is isolated.
   */
  function test(description, fn) {
    try {
      fn();
      results.push({ description: description, passed: true, error: null });
    } catch (err) {
      results.push({ description: description, passed: false, error: err && err.message ? err.message : String(err) });
    }
  }

  /* --- Assertion helpers -------------------------------------------------- */
  function assert(condition, message) {
    if (!condition) {
      throw new Error(message || 'Assertion failed');
    }
  }

  function assertEqual(actual, expected, message) {
    if (actual !== expected) {
      throw new Error((message ? message + ' — ' : '') + 'expected ' + JSON.stringify(expected) + ' but got ' + JSON.stringify(actual));
    }
  }

  function assertArrayEqual(actual, expected, message) {
    const prefix = message ? message + ' — ' : '';
    if (!Array.isArray(actual)) {
      throw new Error(prefix + 'expected an array but got ' + JSON.stringify(actual));
    }
    if (actual.length !== expected.length) {
      throw new Error(prefix + 'expected ' + JSON.stringify(expected) + ' but got ' + JSON.stringify(actual));
    }
    for (let i = 0; i < expected.length; i++) {
      if (actual[i] !== expected[i]) {
        throw new Error(prefix + 'expected ' + JSON.stringify(expected) + ' but got ' + JSON.stringify(actual));
      }
    }
  }

  /* ========================================================================
   * Tests for window.Game functions
   * ====================================================================== */
  const Game = window.Game || {};

  /* --- generateSecretNumber ---------------------------------------------- */
  test('generateSecretNumber: returns a number', function () {
    const n = Game.generateSecretNumber(1, 100);
    assertEqual(typeof n, 'number', 'should return a value of type number');
  });

  test('generateSecretNumber: stays within min and max (50 runs)', function () {
    for (let i = 0; i < 50; i++) {
      const n = Game.generateSecretNumber(1, 100);
      assert(n >= 1 && n <= 100, 'got ' + n + ', which is outside 1..100');
    }
  });

  test('generateSecretNumber: returns a whole number (no decimals)', function () {
    for (let i = 0; i < 50; i++) {
      const n = Game.generateSecretNumber(1, 100);
      assert(Number.isInteger(n), 'got ' + n + ', which is not a whole number');
    }
  });

  /* --- checkGuess --------------------------------------------------------- */
  test("checkGuess: returns 'high' when guess is above secret", function () {
    assertEqual(Game.checkGuess(80, 50), 'high');
  });

  test("checkGuess: returns 'low' when guess is below secret", function () {
    assertEqual(Game.checkGuess(20, 50), 'low');
  });

  test("checkGuess: returns 'correct' when guess equals secret", function () {
    assertEqual(Game.checkGuess(50, 50), 'correct');
  });

  /* --- isGameOver --------------------------------------------------------- */
  test('isGameOver: false when attempts remain and not won', function () {
    assertEqual(Game.isGameOver(3, 10, false), false);
  });

  test('isGameOver: true when the player has won (any attempt count)', function () {
    assertEqual(Game.isGameOver(3, 10, true), true);
  });

  test('isGameOver: true when attempts are used up', function () {
    assertEqual(Game.isGameOver(10, 10, false), true);
  });

  /* --- addToHistory ------------------------------------------------------- */
  test('addToHistory: returns a new array with the score appended', function () {
    assertArrayEqual(Game.addToHistory([3, 7], 5), [3, 7, 5]);
  });

  test('addToHistory: does not mutate the original array', function () {
    const original = [3, 7];
    Game.addToHistory(original, 5);
    assertEqual(original.length, 2, 'the original array length changed — did you push() onto it?');
    assertArrayEqual(original, [3, 7], 'the original array contents changed');
  });

  test('addToHistory: works starting from an empty array', function () {
    assertArrayEqual(Game.addToHistory([], 4), [4]);
  });

  /* --- getLastFiveScores -------------------------------------------------- */
  test('getLastFiveScores: returns all items when there are fewer than 5', function () {
    assertArrayEqual(Game.getLastFiveScores([1, 2, 3]), [1, 2, 3]);
  });

  test('getLastFiveScores: returns exactly 5 items when there are more than 5', function () {
    const out = Game.getLastFiveScores([1, 2, 3, 4, 5, 6, 7]);
    assertEqual(out.length, 5, 'should return exactly 5 items');
  });

  test('getLastFiveScores: returns the LAST 5 items, not the first 5', function () {
    assertArrayEqual(Game.getLastFiveScores([1, 2, 3, 4, 5, 6, 7]), [3, 4, 5, 6, 7]);
  });

  test('getLastFiveScores: returns a copy, not the original array', function () {
    const original = [1, 2, 3];
    const out = Game.getLastFiveScores(original);
    assert(out !== original, 'should return a NEW array, not the same one you were given');
  });

  /* ========================================================================
   * DOM integration tests — confirm the required page elements exist.
   * (These check the scaffold's HTML, which you should not need to edit.)
   * ====================================================================== */
  test("DOM: #guess-input exists", function () {
    assert(document.getElementById('guess-input') !== null, 'missing element with id="guess-input"');
  });

  test("DOM: #guess-btn exists", function () {
    assert(document.getElementById('guess-btn') !== null, 'missing element with id="guess-btn"');
  });

  test("DOM: #message exists", function () {
    assert(document.getElementById('message') !== null, 'missing element with id="message"');
  });

  test("DOM: #history-list exists", function () {
    assert(document.getElementById('history-list') !== null, 'missing element with id="history-list"');
  });

  test("DOM: #restart-btn exists", function () {
    assert(document.getElementById('restart-btn') !== null, 'missing element with id="restart-btn"');
  });

  /* ========================================================================
   * Render the results into #test-results
   * ====================================================================== */
  function render() {
    const container = document.getElementById('test-results');
    if (!container) return;

    container.textContent = '';
    let passing = 0;

    results.forEach(function (r) {
      if (r.passed) passing++;

      const row = document.createElement('div');
      row.className = 'test-row ' + (r.passed ? 'test-pass' : 'test-fail');
      row.textContent = (r.passed ? '✓ ' : '✗ ') + r.description;

      if (!r.passed && r.error) {
        const detail = document.createElement('span');
        detail.className = 'test-error';
        detail.textContent = r.error;
        row.appendChild(detail);
      }

      container.appendChild(row);
    });

    const summary = document.createElement('div');
    summary.className = 'test-summary';
    summary.textContent = passing + ' / ' + results.length + ' tests passing';
    container.appendChild(summary);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', render);
  } else {
    render();
  }
})();
